# Generated by Django 5.1.6 on 2025-03-04 22:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AreasTecnologicas',
            fields=[
                ('id_area_tecnologica', models.BigAutoField(primary_key=True, serialize=False)),
                ('area_tecnologica', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Colaboradores',
            fields=[
                ('id_colaborador', models.BigAutoField(primary_key=True, serialize=False)),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('nome', models.CharField(max_length=256)),
                ('dt_nascimento', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Financiadores',
            fields=[
                ('id_financiador', models.BigAutoField(primary_key=True, serialize=False)),
                ('financiador', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Projetos',
            fields=[
                ('id_projeto', models.BigAutoField(primary_key=True, serialize=False)),
                ('projeto', models.CharField(max_length=100)),
                ('coordenador', models.CharField(max_length=100)),
                ('ativo', models.CharField(choices=[('S', 'Sim'), ('N', 'Não')], default='S', max_length=1)),
                ('inicio_vigencia', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('qtd_membros', models.IntegerField(default=0)),
                ('area_tecnologica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.areastecnologicas')),
                ('equipe', models.ManyToManyField(related_name='projetos', to='my_app.colaboradores')),
                ('financiador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.financiadores')),
            ],
        ),
    ]
